/**********************************************************************************************************************
 * \file isotp.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

#include "isotp.h"
#include "can.h" // Can_SendMsg() 함수를 사용하기 위해 포함
#include "etc.h"
// --- Defines ---
#define ISO_TP_BUFFER_SIZE      4096 // 수신할 수 있는 최대 메시지 크기
#define FC_TIMEOUT_MS 100 // Flow Control 수신 대기 시간 (100ms)

// --- 수신 관련 변수 ---
static isotp_callback_t g_app_callback = NULL;
typedef enum {
    ISO_TP_RX_IDLE,
    ISO_TP_RX_RECEIVING
} IsoTpRxState;

static IsoTpRxState g_rx_state = ISO_TP_RX_IDLE;
static uint8  g_rx_buffer[ISO_TP_BUFFER_SIZE];
static uint16 g_rx_total_len = 0;
static uint16 g_rx_bytes_received = 0;
static uint8  g_rx_expected_seq_num = 0;

// --- 송신 관련 변수 ---
// volatile: 인터럽트(ISR)에서 값이 변경될 수 있음을 컴파일러에게 알림
static volatile boolean g_flow_control_received = FALSE;
static volatile uint8   g_stmin_from_fc = 0;

// --- Private 함수 선언 ---
static void reset_rx_state(void);
static void send_flow_control(uint32 reply_id);

// --- Public 함수 구현 ---

void IsoTp_Init(void) {
    reset_rx_state();
    g_app_callback = NULL;
}


void IsoTp_RegisterCallback(isotp_callback_t callback)
{
    g_app_callback = callback;
}

void IsoTp_RxHandler(uint32 id, uint8* data, uint8 len) {
    uint8 pci_type = data[0] >> 4;

    switch (pci_type) {
        // --- Single Frame (SF) ---
        case 0x0:
            if (g_rx_state == ISO_TP_RX_IDLE && g_app_callback != NULL) {
                uint8 msg_len = data[0] & 0x0F;
                if (msg_len > 0 && msg_len <= 7) {
                    g_app_callback(id, &data[1], msg_len);
                }
            }
            break;

        // --- First Frame (FF) ---
        case 0x1:
            if (g_rx_state == ISO_TP_RX_IDLE) {
                g_rx_total_len = ((uint16)(data[0] & 0x0F) << 8) | data[1];
                if (g_rx_total_len > 0 && g_rx_total_len <= ISO_TP_BUFFER_SIZE) {
                    g_rx_bytes_received = 0;
                    for(int i = 0; i < 6; i++) {
                        if((i + 2) < len) g_rx_buffer[g_rx_bytes_received++] = data[i + 2];
                    }
                    g_rx_expected_seq_num = 1;
                    g_rx_state = ISO_TP_RX_RECEIVING;
                    send_flow_control(id + 8); // UDS 표준 응답 ID
                }
            }
            break;

        // --- Consecutive Frame (CF) ---
        case 0x2:
            if (g_rx_state == ISO_TP_RX_RECEIVING) {
                if ((data[0] & 0x0F) == g_rx_expected_seq_num) {
                    for (int i = 0; i < 7; i++) {
                        if (g_rx_bytes_received < g_rx_total_len && (i + 1) < len) {
                            g_rx_buffer[g_rx_bytes_received++] = data[i + 1];
                        }
                    }
                    g_rx_expected_seq_num = (g_rx_expected_seq_num + 1) % 16;
                    if (g_rx_bytes_received >= g_rx_total_len) {
                        if (g_app_callback != NULL) {
                            g_app_callback(id, g_rx_buffer, g_rx_total_len);
                        }
                        reset_rx_state();
                    }
                } else {
                    reset_rx_state(); // 순서 번호가 틀리면 리셋
                }
            }
            break;

        // --- Flow Control (FC) ---
        case 0x3:
            // CTS (Clear To Send) 상태인지 확인
            if ((data[0] & 0x0F) == 0) {
                g_stmin_from_fc = data[2]; // STmin 값 저장
                g_flow_control_received = TRUE; // Send 함수가 기다리는 플래그를 세워줌
            }
            break;
    }
}


// --- Private Function Implementations ---

static void reset_rx_state(void) {
    g_rx_state = ISO_TP_RX_IDLE;
    g_rx_total_len = 0;
    g_rx_bytes_received = 0;
    g_rx_expected_seq_num = 0;
}


// 수신 준비가 되었다는 Flow Control(FC) 프레임을 송신측에 보냄
static void send_flow_control(uint32 reply_id) {
    uint8 fc_data[8] = {0x30, 0x00, 0x00, 0xAA, 0xAA, 0xAA, 0xAA, 0xAA};
    // 0x30: CTS, BlockSize=0 | 0x00: STmin=0ms | 0xAA: Padding
    Can_SendMsg(reply_id, (const char*)fc_data, 8);
}

sint8 IsoTp_Send(uint32 id, const uint8* data, uint16 len) {
    if (len == 0 || len > ISO_TP_BUFFER_SIZE) {
        return -1;
    }

    // 7바이트 이하 메시지는 Single Frame으로 즉시 전송
    if (len <= 7) {
        uint8 sf_data[8] = {0,};
        sf_data[0] = 0x00 | (uint8)len;
        for(uint16 i = 0; i < len; i++) {
            sf_data[i + 1] = data[i];
        }
        Can_SendMsg(id, (const char*)sf_data, 8);
        return 0;
    }

    // --- 긴 메시지 전송 (블로킹 로직) ---
    // 1. First Frame(FF) 전송
    uint8 ff_data[8] = {0,};
    ff_data[0] = 0x10 | (uint8)(len >> 8);
    ff_data[1] = (uint8)(len & 0xFF);
    for(int i = 0; i < 6; i++) {
        ff_data[i + 2] = data[i];
    }
    Can_SendMsg(id, (const char*)ff_data, 8);

    // 2. Flow Control(FC) 수신 대기
    g_flow_control_received = FALSE;
    uint32 timeout = FC_TIMEOUT_MS;
    while(!g_flow_control_received && timeout > 0) {
        delay_ms(1);
        timeout--;
    }

    if (!g_flow_control_received) {
        return -1; // 타임아웃 실패
    }

    // 3. Consecutive Frame(CF) 순차 전송
    uint16 bytes_sent = 6;
    uint8 seq_num = 1;
    while(bytes_sent < len) {
        uint8 cf_data[8] = {0,};
        cf_data[0] = 0x20 | seq_num;

        uint8 bytes_to_send = 7;
        if ((len - bytes_sent) < 7) {
            bytes_to_send = len - bytes_sent;
        }

        for (uint8 i = 0; i < bytes_to_send; i++) {
            cf_data[i + 1] = data[bytes_sent++];
        }

        Can_SendMsg(id, (const char*)cf_data, 8);
        seq_num = (seq_num + 1) % 16;

        // FC로 수신한 STmin 만큼 딜레이
        if (g_stmin_from_fc > 0) {
            delay_ms(g_stmin_from_fc);
        }
    }
    return 0;
}
/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/



