/**********************************************************************************************************************
 * \file isotp.h
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

#ifndef BSW_DRIVER_ISOTP_H_
#define BSW_DRIVER_ISOTP_H_
#include "Ifx_Types.h"

// 애플리케이션에 완성된 메시지를 전달하기 위한 콜백 함수 포인터 타입
typedef void (*isotp_callback_t)(uint32 id, uint8* data, uint16 len);

// --- Public Function Prototypes ---

void IsoTp_Init(void);
void IsoTp_RegisterCallback(isotp_callback_t callback);
void IsoTp_RxHandler(uint32 id, uint8* data, uint8 len);

/**
 * @brief ISO-TP 메시지를 전송합니다. (블로킹 방식)
 * 이 함수는 전체 메시지 전송이 완료될 때까지 종료되지 않고 기다립니다.
 * @param id    메시지를 보낼 목적지 CAN ID
 * @param data  전송할 데이터 포인터
 * @param len   전송할 데이터 길이
 * @return 0 on success, -1 on failure (e.g., timeout)
 */
sint8 IsoTp_Send(uint32 id, const uint8* data, uint16 len);



//// 애플리케이션에 완성된 메시지를 전달하기 위한 콜백 함수 포인터 타입 정의
//typedef void (*isotp_callback_t)(uint32 id, uint8* data, uint16 len);
//
//// --- Public Function Prototypes ---
//
///**
// * @brief ISO-TP 모듈을 초기화합니다.
// */
//void IsoTp_Init(void);
//
///**
// * @brief ISO-TP 메시지 수신 완료 시 호출될 콜백 함수를 등록합니다.
// * @param callback 애플리케이션의 콜백 함수 포인터
// */
//void IsoTp_RegisterCallback(isotp_callback_t callback);
//
///**
// * @brief CAN 수신 인터럽트에서 호출될 메인 핸들러입니다.
// * 수신된 CAN 프레임을 분석하여 ISO-TP 메시지를 재조립합니다.
// * @param id 수신된 CAN ID
// * @param data 수신된 CAN 데이터 포인터 (최대 8바이트)
// * @param len 수신된 데이터 길이
// */
//void IsoTp_RxHandler(uint32 id, uint8* data, uint8 len);
//void IsoTp_Send(uint32 id, const uint8* data, uint16 len);
/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*-------------------------------------------------Data Structures---------------------------------------------------*/
/*********************************************************************************************************************/
 
/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/


#endif /* BSW_DRIVER_ISOTP_H_ */
